import React from 'react';
import ReactDOM from 'react-dom/client';
import { invoke } from '@tauri-apps/api/core';
import { Store } from '@tauri-apps/plugin-store';
import { enable, disable, isEnabled } from '@tauri-apps/plugin-autostart';
import { BarChart3, Brain, CalendarDays, ChevronDown, ChevronUp, CircleDollarSign, Lightbulb, RefreshCw, Settings, Sparkles, Target, Terminal, Zap } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import './styles.css';
import appIcon from './app-icon.png';

type Day={date:string;claude:number;cursor:number;codex:number;total:number}; type Model={model:string;claude:number;cursor:number;codex:number;total:number};
type Session={id:string;tool:string;cost:number;dominant_model:string;messages:number;title:string};
type Tip={rank:number;title:string;detail:string;wrong:string;right:string};
type Snapshot={asOfDate:string;today:number;month:number;yesterday:number;claudeToday:number;cursorToday:number;codexToday:number;claudeMonth:number;cursorMonth:number;codexMonth:number;sessionsToday:number;messagesToday:number;productBreakdown:Record<string,number>;modelBreakdown:Model[];days:Day[];topSessions:Session[];tips:Tip[];insight?:string;claudePath:string;cursorPath:string;codexPath:string};
const money=(n:number)=>n.toLocaleString('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2});
const modelName=(s:string)=>s.replace('claude-','').replaceAll('-',' ').replace(/\b\w/g,c=>c.toUpperCase());

function App(){
 const [tab,setTab]=React.useState<'dashboard'|'coach'|'settings'>('dashboard'); const [range,setRange]=React.useState('7days'); const [data,setData]=React.useState<Snapshot>(); const [loading,setLoading]=React.useState(false); const [error,setError]=React.useState('');
 const [budget,setBudget]=React.useState(0); const [startup,setStartup]=React.useState(false); const [expanded,setExpanded]=React.useState<number[]>([]);
 const load=React.useCallback(async()=>{setLoading(true);setError('');try{setData(await invoke<Snapshot>('scan_usage',{range}));}catch(e){setError(String(e))}finally{setLoading(false)}},[range]);
 React.useEffect(()=>{load()},[load]); React.useEffect(()=>{(async()=>{const s=await Store.load('settings.json');setBudget(await s.get<number>('budget')??0);setStartup(await isEnabled())})()},[]);
 const saveBudget=async(n:number)=>{setBudget(n);const s=await Store.load('settings.json');await s.set('budget',n);await s.save()};
 const toggleStartup=async(v:boolean)=>{v?await enable():await disable();setStartup(v)};
 const projection=data?data.month/(new Date().getDate())*new Date(new Date().getFullYear(),new Date().getMonth()+1,0).getDate():0;
 return <div className="shell"><aside><div className="brand"><div className="brandmark"><img src={appIcon} alt=""/></div><div><strong>AI Usage</strong><small>LOCAL TRACKER</small></div></div><nav>
  <button className={tab==='dashboard'?'active':''} onClick={()=>setTab('dashboard')}><BarChart3/>Dashboard</button><button className={tab==='coach'?'active':''} onClick={()=>setTab('coach')}><Lightbulb/>Cost coach</button><button className={tab==='settings'?'active':''} onClick={()=>setTab('settings')}><Settings/>Settings</button>
 </nav><div className="local"><span className="dot"/>Local only<small>Your data never leaves this PC</small></div></aside>
 <main><header><div><h1>{tab==='dashboard'?'Usage dashboard':tab==='coach'?'Cost coach':'Settings'}</h1><p>{tab==='dashboard'?'Claude Code + Cursor + OpenAI Codex from local sessions':tab==='coach'?'Same results, fewer turns.':'Configure your local tracker'}</p></div><button className="refresh" onClick={load} disabled={loading}><RefreshCw className={loading?'spin':''}/>{loading?'Scanning…':'Refresh'}</button></header>
 {error&&<div className="error">{error}</div>}{!data?<div className="loading">Scanning local AI sessions…</div>:tab==='dashboard'?<Dashboard data={data} range={range} setRange={setRange} budget={budget} projection={projection}/>:tab==='coach'?<Coach data={data} budget={budget} saveBudget={saveBudget} projection={projection} expanded={expanded} setExpanded={setExpanded}/>:<SettingsPage data={data} startup={startup} toggleStartup={toggleStartup}/>}</main></div>
}

function Dashboard({data,range,setRange,budget,projection}:{data:Snapshot;range:string;setRange:(x:string)=>void;budget:number;projection:number}){const delta=data.yesterday?((data.today-data.yesterday)/data.yesterday)*100:0;return <>
 <div className="toolbar"><div className="asof"><CalendarDays/>Data as of <b>{data.asOfDate}</b></div><div className="segments">{[['today','Today'],['7days','7 Days'],['month','This Month']].map(([v,l])=><button key={v} className={range===v?'active':''} onClick={()=>setRange(v)}>{l}</button>)}</div></div>
 {budget>0&&projection>budget&&<div className="budget-alert"><Target/>Projected {money(projection)} this month — above your {money(budget)} budget.</div>}
 <section className="cards"><Card icon={<CircleDollarSign/>} label="TODAY" value={money(data.today)} note={data.yesterday?`${delta>=0?'↑':'↓'} ${Math.abs(delta).toFixed(0)}% vs yesterday`:'No previous-day baseline'}/><Card icon={<CalendarDays/>} label="THIS MONTH" value={money(data.month)} note={`Claude ${money(data.claudeMonth)} · Cursor ${money(data.cursorMonth)} · Codex ${money(data.codexMonth)}`}/><Card icon={<Brain/>} label="CLAUDE TODAY" value={money(data.claudeToday)} note="Estimated at list price" accent="purple"/><Card icon={<Zap/>} label="CODEX TODAY" value={money(data.codexToday)} note="API-equivalent estimate" accent="green"/><Card icon={<Terminal/>} label="SESSIONS TODAY" value={String(data.sessionsToday)} note={`${data.messagesToday} priced usage events`} accent="orange"/></section>
 <section className="panel chart"><div className="panel-title"><div><h2>Spend over time</h2><p>Daily estimated cost by tool</p></div><div className="legend-note">USD</div></div><ResponsiveContainer width="100%" height={265}><BarChart data={data.days} barGap={2}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date" tickFormatter={v=>v.slice(5)} /><YAxis tickFormatter={v=>`$${v}`}/><Tooltip formatter={(v)=>money(Number(v))}/><Legend/><Bar dataKey="claude" name="Claude" fill="#7357e8" radius={[4,4,0,0]}/><Bar dataKey="cursor" name="Cursor" fill="#ef9b45" radius={[4,4,0,0]}/><Bar dataKey="codex" name="Codex" fill="#2eaa78" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></section>
 <section className="panel"><div className="panel-title"><div><h2>Spend by model</h2><p>Cost attribution across local sessions</p></div></div><table><thead><tr><th>MODEL</th><th>CLAUDE</th><th>CURSOR</th><th>CODEX</th><th>TOTAL</th></tr></thead><tbody>{data.modelBreakdown.length?data.modelBreakdown.sort((a,b)=>b.total-a.total).map(m=><tr key={m.model}><td><span className="model-dot"/>{modelName(m.model)}</td><td>{money(m.claude)}</td><td>{money(m.cursor)}</td><td>{money(m.codex)}</td><td><b>{money(m.total)}</b></td></tr>):<tr><td colSpan={5} className="empty">No priced sessions in this range.</td></tr>}</tbody></table></section><p className="estimate-note">Claude and Codex are API-equivalent list-price estimates. Cursor is estimated from locally available token data.</p></>}
function Card({icon,label,value,note,accent='blue'}:{icon:React.ReactNode;label:string;value:string;note:string;accent?:string}){return <div className="card"><div className={`card-icon ${accent}`}>{icon}</div><small>{label}</small><strong>{value}</strong><p>{note}</p></div>}

function Coach({data,budget,saveBudget,projection,expanded,setExpanded}:{data:Snapshot;budget:number;saveBudget:(n:number)=>void;projection:number;expanded:number[];setExpanded:(n:number[])=>void}){return <div className="coach-grid"><div><section className="panel"><div className="panel-title"><div><h2>Today's most expensive sessions</h2><p>Where your tokens went</p></div></div>{data.topSessions.length?data.topSessions.map((s,i)=><div className="session"><span className="rank">{i+1}</span><div><b>{s.title}</b><div className="tags"><i>{s.tool}</i><i>{modelName(s.dominant_model)}</i><i>{s.messages} messages</i></div><p><Lightbulb/> {s.dominant_model.includes('opus')?'Mostly Opus — use Sonnet for edits and Q&A.':s.messages>=15?'Front-load context to reduce back-and-forth.':'State the goal and setup up front.'}</p></div><strong>{money(s.cost)}</strong></div>):<div className="empty">No priced sessions found for today.</div>}</section>
 <section className="panel tips"><div className="panel-title"><div><h2>Top ways to cut cost</h2><p>Rotates daily</p></div></div>{data.insight&&<div className="insight"><Sparkles/>{data.insight}</div>}{data.tips.map(t=><div className="tip"><span className="rank">{t.rank}</span><div><b>{t.title}</b><p>{t.detail}</p>{expanded.includes(t.rank)&&<div className="examples"><span>✕ {t.wrong}</span><span>✓ {t.right}</span></div>}</div><button onClick={()=>setExpanded(expanded.includes(t.rank)?expanded.filter(x=>x!==t.rank):[...expanded,t.rank])}>{expanded.includes(t.rank)?<ChevronUp/>:<ChevronDown/>}</button></div>)}</section></div>
 <aside className="right"><section className="panel budget"><Target/><h2>Monthly budget</h2><p>Get warned when projected usage runs over your cap.</p><label>MONTHLY CAP (USD)<input type="number" min="0" step="5" value={budget||''} placeholder="0" onChange={e=>saveBudget(Number(e.target.value))}/></label>{budget>0&&<div className="projection"><span>Month to date <b>{money(data.month)}</b></span><span>Projected <b>{money(projection)}</b></span><progress max={budget} value={Math.min(projection,budget)}/></div>}</section></aside></div>}

function SettingsPage({data,startup,toggleStartup}:{data:Snapshot;startup:boolean;toggleStartup:(v:boolean)=>void}){return <div className="settings-grid"><section className="panel settings-panel"><h2>Data sources</h2><p>The tracker scans local files in read-only mode.</p><PathRow title="Claude Code sessions" path={data.claudePath} ok/><PathRow title="Cursor local database" path={data.cursorPath} ok={data.cursorToday>0||data.cursorMonth>0}/><PathRow title="OpenAI Codex sessions" path={data.codexPath} ok={data.codexToday>0||data.codexMonth>0}/></section><section className="panel settings-panel"><h2>Desktop</h2><label className="toggle-row"><div><b>Start at login</b><p>Keep usage available from the menu bar or system tray.</p></div><input type="checkbox" checked={startup} onChange={e=>toggleStartup(e.target.checked)}/></label><div className="notice">Closing the window keeps AI Usage Tracker running in the macOS menu bar or Windows system tray. Use the tray menu to quit.</div></section><section className="panel settings-panel"><h2>Privacy</h2><p>No analytics, cloud sync, or external API calls. Session contents are never displayed or uploaded; only local token counts and metadata are aggregated.</p></section></div>}
function PathRow({title,path,ok}:{title:string;path:string;ok:boolean}){return <div className="pathrow"><span className={ok?'status ok':'status'}/><div><b>{title}</b><code>{path}</code></div></div>}
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
